<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Core\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AFG', 'phone_code' => '+93', 'is_active' => true],
            ['name' => 'Åland Islands', 'code' => 'ALA', 'phone_code' => '+358', 'is_active' => true],
            ['name' => 'Albania', 'code' => 'ALB', 'phone_code' => '+355', 'is_active' => true],
            ['name' => 'Algeria', 'code' => 'DZA', 'phone_code' => '+213', 'is_active' => true],
            ['name' => 'American Samoa', 'code' => 'ASM', 'phone_code' => '+1-684', 'is_active' => true],
            ['name' => 'Andorra', 'code' => 'AND', 'phone_code' => '+376', 'is_active' => true],
            ['name' => 'Angola', 'code' => 'AGO', 'phone_code' => '+244', 'is_active' => true],
            ['name' => 'Anguilla', 'code' => 'AIA', 'phone_code' => '+1-264', 'is_active' => true],
            ['name' => 'Antarctica', 'code' => 'ATA', 'phone_code' => '+672', 'is_active' => true],
            ['name' => 'Antigua and Barbuda', 'code' => 'ATG', 'phone_code' => '+1-268', 'is_active' => true],
            ['name' => 'Argentina', 'code' => 'ARG', 'phone_code' => '+54', 'is_active' => true],
            ['name' => 'Armenia', 'code' => 'ARM', 'phone_code' => '+374', 'is_active' => true],
            ['name' => 'Aruba', 'code' => 'ABW', 'phone_code' => '+297', 'is_active' => true],
            ['name' => 'Australia', 'code' => 'AUS', 'phone_code' => '+61', 'is_active' => true],
            ['name' => 'Austria', 'code' => 'AUT', 'phone_code' => '+43', 'is_active' => true],
            ['name' => 'Azerbaijan', 'code' => 'AZE', 'phone_code' => '+994', 'is_active' => true],
            ['name' => 'Bahamas', 'code' => 'BHS', 'phone_code' => '+1-242', 'is_active' => true],
            ['name' => 'Bahrain', 'code' => 'BHR', 'phone_code' => '+973', 'is_active' => true],
            ['name' => 'Bangladesh', 'code' => 'BGD', 'phone_code' => '+880', 'is_active' => true],
            ['name' => 'Barbados', 'code' => 'BRB', 'phone_code' => '+1-246', 'is_active' => true],
            ['name' => 'Belarus', 'code' => 'BLR', 'phone_code' => '+375', 'is_active' => true],
            ['name' => 'Belgium', 'code' => 'BEL', 'phone_code' => '+32', 'is_active' => true],
            ['name' => 'Belize', 'code' => 'BLZ', 'phone_code' => '+501', 'is_active' => true],
            ['name' => 'Benin', 'code' => 'BEN', 'phone_code' => '+229', 'is_active' => true],
            ['name' => 'Bermuda', 'code' => 'BMU', 'phone_code' => '+1-441', 'is_active' => true],
            ['name' => 'Bhutan', 'code' => 'BTN', 'phone_code' => '+975', 'is_active' => true],
            ['name' => 'Bolivia (Plurinational State of)', 'code' => 'BOL', 'phone_code' => '+591', 'is_active' => true],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BES', 'phone_code' => '+599', 'is_active' => true],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BIH', 'phone_code' => '+387', 'is_active' => true],
            ['name' => 'Botswana', 'code' => 'BWA', 'phone_code' => '+267', 'is_active' => true],
            ['name' => 'Bouvet Island', 'code' => 'BVT', 'phone_code' => '+47', 'is_active' => true],
            ['name' => 'Brazil', 'code' => 'BRA', 'phone_code' => '+55', 'is_active' => true],
            ['name' => 'British Indian Ocean Territory', 'code' => 'IOT', 'phone_code' => '+246', 'is_active' => true],
            ['name' => 'Brunei Darussalam', 'code' => 'BRN', 'phone_code' => '+673', 'is_active' => true],
            ['name' => 'Bulgaria', 'code' => 'BGR', 'phone_code' => '+359', 'is_active' => true],
            ['name' => 'Burkina Faso', 'code' => 'BFA', 'phone_code' => '+226', 'is_active' => true],
            ['name' => 'Burundi', 'code' => 'BDI', 'phone_code' => '+257', 'is_active' => true],
            ['name' => 'Cabo Verde', 'code' => 'CPV', 'phone_code' => '+238', 'is_active' => true],
            ['name' => 'Cambodia', 'code' => 'KHM', 'phone_code' => '+855', 'is_active' => true],
            ['name' => 'Cameroon', 'code' => 'CMR', 'phone_code' => '+237', 'is_active' => true],
            ['name' => 'Canada', 'code' => 'CAN', 'phone_code' => '+1', 'is_active' => true],
            ['name' => 'Cayman Islands', 'code' => 'CYM', 'phone_code' => '+1-345', 'is_active' => true],
            ['name' => 'Central African Republic', 'code' => 'CAF', 'phone_code' => '+236', 'is_active' => true],
            ['name' => 'Chad', 'code' => 'TCD', 'phone_code' => '+235', 'is_active' => true],
            ['name' => 'Chile', 'code' => 'CHL', 'phone_code' => '+56', 'is_active' => true],
            ['name' => 'China', 'code' => 'CHN', 'phone_code' => '+86', 'is_active' => true],
            ['name' => 'Christmas Island', 'code' => 'CXR', 'phone_code' => '+61', 'is_active' => true],
            ['name' => 'Cocos (Keeling) Islands', 'code' => 'CCK', 'phone_code' => '+61', 'is_active' => true],
            ['name' => 'Colombia', 'code' => 'COL', 'phone_code' => '+57', 'is_active' => true],
            ['name' => 'Comoros', 'code' => 'COM', 'phone_code' => '+269', 'is_active' => true],
            ['name' => 'Congo', 'code' => 'COG', 'phone_code' => '+242', 'is_active' => true],
            ['name' => 'Congo (Democratic Republic of the)', 'code' => 'COD', 'phone_code' => '+243', 'is_active' => true],
            ['name' => 'Cook Islands', 'code' => 'COK', 'phone_code' => '+682', 'is_active' => true],
            ['name' => 'Costa Rica', 'code' => 'CRI', 'phone_code' => '+506', 'is_active' => true],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CIV', 'phone_code' => '+225', 'is_active' => true],
            ['name' => 'Croatia', 'code' => 'HRV', 'phone_code' => '+385', 'is_active' => true],
            ['name' => 'Cuba', 'code' => 'CUB', 'phone_code' => '+53', 'is_active' => true],
            ['name' => 'Curaçao', 'code' => 'CUW', 'phone_code' => '+599', 'is_active' => true],
            ['name' => 'Cyprus', 'code' => 'CYP', 'phone_code' => '+357', 'is_active' => true],
            ['name' => 'Czechia', 'code' => 'CZE', 'phone_code' => '+420', 'is_active' => true],
            ['name' => 'Denmark', 'code' => 'DNK', 'phone_code' => '+45', 'is_active' => true],
            ['name' => 'Djibouti', 'code' => 'DJI', 'phone_code' => '+253', 'is_active' => true],
            ['name' => 'Dominica', 'code' => 'DMA', 'phone_code' => '+1-767', 'is_active' => true],
            ['name' => 'Dominican Republic', 'code' => 'DOM', 'phone_code' => '+1-809', 'is_active' => true],
            ['name' => 'Ecuador', 'code' => 'ECU', 'phone_code' => '+593', 'is_active' => true],
            ['name' => 'Egypt', 'code' => 'EGY', 'phone_code' => '+20', 'is_active' => true],
            ['name' => 'El Salvador', 'code' => 'SLV', 'phone_code' => '+503', 'is_active' => true],
            ['name' => 'Equatorial Guinea', 'code' => 'GNQ', 'phone_code' => '+240', 'is_active' => true],
            ['name' => 'Eritrea', 'code' => 'ERI', 'phone_code' => '+291', 'is_active' => true],
            ['name' => 'Estonia', 'code' => 'EST', 'phone_code' => '+372', 'is_active' => true],
            ['name' => 'Eswatini', 'code' => 'SWZ', 'phone_code' => '+268', 'is_active' => true],
            ['name' => 'Ethiopia', 'code' => 'ETH', 'phone_code' => '+251', 'is_active' => true],
            ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FLK', 'phone_code' => '+500', 'is_active' => true],
            ['name' => 'Faroe Islands', 'code' => 'FRO', 'phone_code' => '+298', 'is_active' => true],
            ['name' => 'Fiji', 'code' => 'FJI', 'phone_code' => '+679', 'is_active' => true],
            ['name' => 'Finland', 'code' => 'FIN', 'phone_code' => '+358', 'is_active' => true],
            ['name' => 'France', 'code' => 'FRA', 'phone_code' => '+33', 'is_active' => true],
            ['name' => 'French Guiana', 'code' => 'GUF', 'phone_code' => '+594', 'is_active' => true],
            ['name' => 'French Polynesia', 'code' => 'PYF', 'phone_code' => '+689', 'is_active' => true],
            ['name' => 'French Southern Territories', 'code' => 'ATF', 'phone_code' => '+262', 'is_active' => true],
            ['name' => 'Gabon', 'code' => 'GAB', 'phone_code' => '+241', 'is_active' => true],
            ['name' => 'Gambia', 'code' => 'GMB', 'phone_code' => '+220', 'is_active' => true],
            ['name' => 'Georgia', 'code' => 'GEO', 'phone_code' => '+995', 'is_active' => true],
            ['name' => 'Germany', 'code' => 'DEU', 'phone_code' => '+49', 'is_active' => true],
            ['name' => 'Ghana', 'code' => 'GHA', 'phone_code' => '+233', 'is_active' => true],
            ['name' => 'Gibraltar', 'code' => 'GIB', 'phone_code' => '+350', 'is_active' => true],
            ['name' => 'Greece', 'code' => 'GRC', 'phone_code' => '+30', 'is_active' => true],
            ['name' => 'Greenland', 'code' => 'GRL', 'phone_code' => '+299', 'is_active' => true],
            ['name' => 'Grenada', 'code' => 'GRD', 'phone_code' => '+1-473', 'is_active' => true],
            ['name' => 'Guadeloupe', 'code' => 'GLP', 'phone_code' => '+590', 'is_active' => true],
            ['name' => 'Guam', 'code' => 'GUM', 'phone_code' => '+1-671', 'is_active' => true],
            ['name' => 'Guatemala', 'code' => 'GTM', 'phone_code' => '+502', 'is_active' => true],
            ['name' => 'Guernsey', 'code' => 'GGY', 'phone_code' => '+44-1481', 'is_active' => true],
            ['name' => 'Guinea', 'code' => 'GIN', 'phone_code' => '+224', 'is_active' => true],
            ['name' => 'Guinea-Bissau', 'code' => 'GNB', 'phone_code' => '+245', 'is_active' => true],
            ['name' => 'Guyana', 'code' => 'GUY', 'phone_code' => '+592', 'is_active' => true],
            ['name' => 'Haiti', 'code' => 'HTI', 'phone_code' => '+509', 'is_active' => true],
            ['name' => 'Heard Island and McDonald Islands', 'code' => 'HMD', 'phone_code' => '+672', 'is_active' => true],
            ['name' => 'Holy See', 'code' => 'VAT', 'phone_code' => '+39', 'is_active' => true],
            ['name' => 'Honduras', 'code' => 'HND', 'phone_code' => '+504', 'is_active' => true],
            ['name' => 'Hong Kong', 'code' => 'HKG', 'phone_code' => '+852', 'is_active' => true],
            ['name' => 'Hungary', 'code' => 'HUN', 'phone_code' => '+36', 'is_active' => true],
            ['name' => 'Iceland', 'code' => 'ISL', 'phone_code' => '+354', 'is_active' => true],
            ['name' => 'India', 'code' => 'IND', 'phone_code' => '+91', 'is_active' => true],
            ['name' => 'Indonesia', 'code' => 'IDN', 'phone_code' => '+62', 'is_active' => true],
            ['name' => 'Iran (Islamic Republic of)', 'code' => 'IRN', 'phone_code' => '+98', 'is_active' => true],
            ['name' => 'Iraq', 'code' => 'IRQ', 'phone_code' => '+964', 'is_active' => true],
            ['name' => 'Ireland', 'code' => 'IRL', 'phone_code' => '+353', 'is_active' => true],
            ['name' => 'Isle of Man', 'code' => 'IMN', 'phone_code' => '+44-1624', 'is_active' => true],
            ['name' => 'Israel', 'code' => 'ISR', 'phone_code' => '+972', 'is_active' => true],
            ['name' => 'Italy', 'code' => 'ITA', 'phone_code' => '+39', 'is_active' => true],
            ['name' => 'Jamaica', 'code' => 'JAM', 'phone_code' => '+1-876', 'is_active' => true],
            ['name' => 'Japan', 'code' => 'JPN', 'phone_code' => '+81', 'is_active' => true],
            ['name' => 'Jersey', 'code' => 'JEY', 'phone_code' => '+44-1534', 'is_active' => true],
            ['name' => 'Jordan', 'code' => 'JOR', 'phone_code' => '+962', 'is_active' => true],
            ['name' => 'Kazakhstan', 'code' => 'KAZ', 'phone_code' => '+7', 'is_active' => true],
            ['name' => 'Kenya', 'code' => 'KEN', 'phone_code' => '+254', 'is_active' => true],
            ['name' => 'Kiribati', 'code' => 'KIR', 'phone_code' => '+686', 'is_active' => true],
            ['name' => 'Korea (Democratic People\'s Republic of)', 'code' => 'PRK', 'phone_code' => '+850', 'is_active' => true],
            ['name' => 'Korea (Republic of)', 'code' => 'KOR', 'phone_code' => '+82', 'is_active' => true],
            ['name' => 'Kuwait', 'code' => 'KWT', 'phone_code' => '+965', 'is_active' => true],
            ['name' => 'Kyrgyzstan', 'code' => 'KGZ', 'phone_code' => '+996', 'is_active' => true],
            ['name' => 'Lao People\'s Democratic Republic', 'code' => 'LAO', 'phone_code' => '+856', 'is_active' => true],
            ['name' => 'Latvia', 'code' => 'LVA', 'phone_code' => '+371', 'is_active' => true],
            ['name' => 'Lebanon', 'code' => 'LBN', 'phone_code' => '+961', 'is_active' => true],
            ['name' => 'Lesotho', 'code' => 'LSO', 'phone_code' => '+266', 'is_active' => true],
            ['name' => 'Liberia', 'code' => 'LBR', 'phone_code' => '+231', 'is_active' => true],
            ['name' => 'Libya', 'code' => 'LBY', 'phone_code' => '+218', 'is_active' => true],
            ['name' => 'Liechtenstein', 'code' => 'LIE', 'phone_code' => '+423', 'is_active' => true],
            ['name' => 'Lithuania', 'code' => 'LTU', 'phone_code' => '+370', 'is_active' => true],
            ['name' => 'Luxembourg', 'code' => 'LUX', 'phone_code' => '+352', 'is_active' => true],
            ['name' => 'Macao', 'code' => 'MAC', 'phone_code' => '+853', 'is_active' => true],
            ['name' => 'Madagascar', 'code' => 'MDG', 'phone_code' => '+261', 'is_active' => true],
            ['name' => 'Malawi', 'code' => 'MWI', 'phone_code' => '+265', 'is_active' => true],
            ['name' => 'Malaysia', 'code' => 'MYS', 'phone_code' => '+60', 'is_active' => true],
            ['name' => 'Maldives', 'code' => 'MDV', 'phone_code' => '+960', 'is_active' => true],
            ['name' => 'Mali', 'code' => 'MLI', 'phone_code' => '+223', 'is_active' => true],
            ['name' => 'Malta', 'code' => 'MLT', 'phone_code' => '+356', 'is_active' => true],
            ['name' => 'Marshall Islands', 'code' => 'MHL', 'phone_code' => '+692', 'is_active' => true],
            ['name' => 'Martinique', 'code' => 'MTQ', 'phone_code' => '+596', 'is_active' => true],
            ['name' => 'Mauritania', 'code' => 'MRT', 'phone_code' => '+222', 'is_active' => true],
            ['name' => 'Mauritius', 'code' => 'MUS', 'phone_code' => '+230', 'is_active' => true],
            ['name' => 'Mayotte', 'code' => 'MYT', 'phone_code' => '+262', 'is_active' => true],
            ['name' => 'Mexico', 'code' => 'MEX', 'phone_code' => '+52', 'is_active' => true],
            ['name' => 'Micronesia (Federated States of)', 'code' => 'FSM', 'phone_code' => '+691', 'is_active' => true],
            ['name' => 'Moldova (Republic of)', 'code' => 'MDA', 'phone_code' => '+373', 'is_active' => true],
            ['name' => 'Monaco', 'code' => 'MCO', 'phone_code' => '+377', 'is_active' => true],
            ['name' => 'Mongolia', 'code' => 'MNG', 'phone_code' => '+976', 'is_active' => true],
            ['name' => 'Montenegro', 'code' => 'MNE', 'phone_code' => '+382', 'is_active' => true],
            ['name' => 'Montserrat', 'code' => 'MSR', 'phone_code' => '+1-664', 'is_active' => true],
            ['name' => 'Morocco', 'code' => 'MAR', 'phone_code' => '+212', 'is_active' => true],
            ['name' => 'Mozambique', 'code' => 'MOZ', 'phone_code' => '+258', 'is_active' => true],
            ['name' => 'Myanmar', 'code' => 'MMR', 'phone_code' => '+95', 'is_active' => true],
            ['name' => 'Namibia', 'code' => 'NAM', 'phone_code' => '+264', 'is_active' => true],
            ['name' => 'Nauru', 'code' => 'NRU', 'phone_code' => '+674', 'is_active' => true],
            ['name' => 'Nepal', 'code' => 'NPL', 'phone_code' => '+977', 'is_active' => true],
            ['name' => 'Netherlands', 'code' => 'NLD', 'phone_code' => '+31', 'is_active' => true],
            ['name' => 'New Caledonia', 'code' => 'NCL', 'phone_code' => '+687', 'is_active' => true],
            ['name' => 'New Zealand', 'code' => 'NZL', 'phone_code' => '+64', 'is_active' => true],
            ['name' => 'Nicaragua', 'code' => 'NIC', 'phone_code' => '+505', 'is_active' => true],
            ['name' => 'Niger', 'code' => 'NER', 'phone_code' => '+227', 'is_active' => true],
            ['name' => 'Nigeria', 'code' => 'NGA', 'phone_code' => '+234', 'is_active' => true],
            ['name' => 'Niue', 'code' => 'NIU', 'phone_code' => '+683', 'is_active' => true],
            ['name' => 'Norfolk Island', 'code' => 'NFK', 'phone_code' => '+672', 'is_active' => true],
            ['name' => 'North Macedonia', 'code' => 'MKD', 'phone_code' => '+389', 'is_active' => true],
            ['name' => 'Northern Mariana Islands', 'code' => 'MNP', 'phone_code' => '+1-670', 'is_active' => true],
            ['name' => 'Norway', 'code' => 'NOR', 'phone_code' => '+47', 'is_active' => true],
            ['name' => 'Oman', 'code' => 'OMN', 'phone_code' => '+968', 'is_active' => true],
            ['name' => 'Pakistan', 'code' => 'PAK', 'phone_code' => '+92', 'is_active' => true],
            ['name' => 'Palau', 'code' => 'PLW', 'phone_code' => '+680', 'is_active' => true],
            ['name' => 'Palestine, State of', 'code' => 'PSE', 'phone_code' => '+970', 'is_active' => true],
            ['name' => 'Panama', 'code' => 'PAN', 'phone_code' => '+507', 'is_active' => true],
            ['name' => 'Papua New Guinea', 'code' => 'PNG', 'phone_code' => '+675', 'is_active' => true],
            ['name' => 'Paraguay', 'code' => 'PRY', 'phone_code' => '+595', 'is_active' => true],
            ['name' => 'Peru', 'code' => 'PER', 'phone_code' => '+51', 'is_active' => true],
            ['name' => 'Philippines', 'code' => 'PHL', 'phone_code' => '+63', 'is_active' => true],
            ['name' => 'Pitcairn', 'code' => 'PCN', 'phone_code' => '+64', 'is_active' => true],
            ['name' => 'Poland', 'code' => 'POL', 'phone_code' => '+48', 'is_active' => true],
            ['name' => 'Portugal', 'code' => 'PRT', 'phone_code' => '+351', 'is_active' => true],
            ['name' => 'Puerto Rico', 'code' => 'PRI', 'phone_code' => '+1-787', 'is_active' => true],
            ['name' => 'Qatar', 'code' => 'QAT', 'phone_code' => '+974', 'is_active' => true],
            ['name' => 'Réunion', 'code' => 'REU', 'phone_code' => '+262', 'is_active' => true],
            ['name' => 'Romania', 'code' => 'ROU', 'phone_code' => '+40', 'is_active' => true],
            ['name' => 'Russian Federation', 'code' => 'RUS', 'phone_code' => '+7', 'is_active' => true],
            ['name' => 'Rwanda', 'code' => 'RWA', 'phone_code' => '+250', 'is_active' => true],
            ['name' => 'Saint Barthélemy', 'code' => 'BLM', 'phone_code' => '+590', 'is_active' => true],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SHN', 'phone_code' => '+290', 'is_active' => true],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KNA', 'phone_code' => '+1-869', 'is_active' => true],
            ['name' => 'Saint Lucia', 'code' => 'LCA', 'phone_code' => '+1-758', 'is_active' => true],
            ['name' => 'Saint Martin (French part)', 'code' => 'MAF', 'phone_code' => '+590', 'is_active' => true],
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'SPM', 'phone_code' => '+508', 'is_active' => true],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VCT', 'phone_code' => '+1-784', 'is_active' => true],
            ['name' => 'Samoa', 'code' => 'WSM', 'phone_code' => '+685', 'is_active' => true],
            ['name' => 'San Marino', 'code' => 'SMR', 'phone_code' => '+378', 'is_active' => true],
            ['name' => 'Sao Tome and Principe', 'code' => 'STP', 'phone_code' => '+239', 'is_active' => true],
            ['name' => 'Saudi Arabia', 'code' => 'SAU', 'phone_code' => '+966', 'is_active' => true],
            ['name' => 'Senegal', 'code' => 'SEN', 'phone_code' => '+221', 'is_active' => true],
            ['name' => 'Serbia', 'code' => 'SRB', 'phone_code' => '+381', 'is_active' => true],
            ['name' => 'Seychelles', 'code' => 'SYC', 'phone_code' => '+248', 'is_active' => true],
            ['name' => 'Sierra Leone', 'code' => 'SLE', 'phone_code' => '+232', 'is_active' => true],
            ['name' => 'Singapore', 'code' => 'SGP', 'phone_code' => '+65', 'is_active' => true],
            ['name' => 'Sint Maarten (Dutch part)', 'code' => 'SXM', 'phone_code' => '+1-721', 'is_active' => true],
            ['name' => 'Slovakia', 'code' => 'SVK', 'phone_code' => '+421', 'is_active' => true],
            ['name' => 'Slovenia', 'code' => 'SVN', 'phone_code' => '+386', 'is_active' => true],
            ['name' => 'Solomon Islands', 'code' => 'SLB', 'phone_code' => '+677', 'is_active' => true],
            ['name' => 'Somalia', 'code' => 'SOM', 'phone_code' => '+252', 'is_active' => true],
            ['name' => 'South Africa', 'code' => 'ZAF', 'phone_code' => '+27', 'is_active' => true],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'SGS', 'phone_code' => '+500', 'is_active' => true],
            ['name' => 'South Sudan', 'code' => 'SSD', 'phone_code' => '+211', 'is_active' => true],
            ['name' => 'Spain', 'code' => 'ESP', 'phone_code' => '+34', 'is_active' => true],
            ['name' => 'Sri Lanka', 'code' => 'LKA', 'phone_code' => '+94', 'is_active' => true],
            ['name' => 'Sudan', 'code' => 'SDN', 'phone_code' => '+249', 'is_active' => true],
            ['name' => 'Suriname', 'code' => 'SUR', 'phone_code' => '+597', 'is_active' => true],
            ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJM', 'phone_code' => '+47', 'is_active' => true],
            ['name' => 'Sweden', 'code' => 'SWE', 'phone_code' => '+46', 'is_active' => true],
            ['name' => 'Switzerland', 'code' => 'CHE', 'phone_code' => '+41', 'is_active' => true],
            ['name' => 'Syrian Arab Republic', 'code' => 'SYR', 'phone_code' => '+963', 'is_active' => true],
            ['name' => 'Tajikistan', 'code' => 'TJK', 'phone_code' => '+992', 'is_active' => true],
            ['name' => 'Tanzania, United Republic of', 'code' => 'TZA', 'phone_code' => '+255', 'is_active' => true],
            ['name' => 'Thailand', 'code' => 'THA', 'phone_code' => '+66', 'is_active' => true],
            ['name' => 'Timor-Leste', 'code' => 'TLS', 'phone_code' => '+670', 'is_active' => true],
            ['name' => 'Togo', 'code' => 'TGO', 'phone_code' => '+228', 'is_active' => true],
            ['name' => 'Tokelau', 'code' => 'TKL', 'phone_code' => '+690', 'is_active' => true],
            ['name' => 'Tonga', 'code' => 'TON', 'phone_code' => '+676', 'is_active' => true],
            ['name' => 'Trinidad and Tobago', 'code' => 'TTO', 'phone_code' => '+1-868', 'is_active' => true],
            ['name' => 'Tunisia', 'code' => 'TUN', 'phone_code' => '+216', 'is_active' => true],
            ['name' => 'Turkey', 'code' => 'TUR', 'phone_code' => '+90', 'is_active' => true],
            ['name' => 'Turkmenistan', 'code' => 'TKM', 'phone_code' => '+993', 'is_active' => true],
            ['name' => 'Turks and Caicos Islands', 'code' => 'TCA', 'phone_code' => '+1-649', 'is_active' => true],
            ['name' => 'Tuvalu', 'code' => 'TUV', 'phone_code' => '+688', 'is_active' => true],
            ['name' => 'Uganda', 'code' => 'UGA', 'phone_code' => '+256', 'is_active' => true],
            ['name' => 'Ukraine', 'code' => 'UKR', 'phone_code' => '+380', 'is_active' => true],
            ['name' => 'United Arab Emirates', 'code' => 'ARE', 'phone_code' => '+971', 'is_active' => true],
            ['name' => 'United Kingdom of Great Britain and Northern Ireland', 'code' => 'GBR', 'phone_code' => '+44', 'is_active' => true],
            ['name' => 'United States of America', 'code' => 'USA', 'phone_code' => '+1', 'is_active' => true],
            ['name' => 'United States Minor Outlying Islands', 'code' => 'UMI', 'phone_code' => '+1', 'is_active' => true],
            ['name' => 'Uruguay', 'code' => 'URY', 'phone_code' => '+598', 'is_active' => true],
            ['name' => 'Uzbekistan', 'code' => 'UZB', 'phone_code' => '+998', 'is_active' => true],
            ['name' => 'Vanuatu', 'code' => 'VUT', 'phone_code' => '+678', 'is_active' => true],
            ['name' => 'Venezuela (Bolivarian Republic of)', 'code' => 'VEN', 'phone_code' => '+58', 'is_active' => true],
            ['name' => 'Viet Nam', 'code' => 'VNM', 'phone_code' => '+84', 'is_active' => true],
            ['name' => 'Wallis and Futuna', 'code' => 'WLF', 'phone_code' => '+681', 'is_active' => true],
            ['name' => 'Western Sahara', 'code' => 'ESH', 'phone_code' => '+212', 'is_active' => true],
            ['name' => 'Yemen', 'code' => 'YEM', 'phone_code' => '+967', 'is_active' => true],
            ['name' => 'Zambia', 'code' => 'ZMB', 'phone_code' => '+260', 'is_active' => true],
            ['name' => 'Zimbabwe', 'code' => 'ZWE', 'phone_code' => '+263', 'is_active' => true],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['code' => $country['code']],
                [
                    'name' => $country['name'],
                    'phone_code' => $country['phone_code'],
                    'is_active' => $country['is_active'],
                ]
            );
        }
    }
}